sjmap=[
    "圈圈环礁湖 Loopy Lagoon",
    "林间小径 Forest Path",
    "苍蓝洞穴 Azure Caverns",
    "崩坏天际线 Collapsing Skyline",
    "眼见为实 Seeing is Believing",
    "午夜之巅 Midnight Spire",
    "节奏山脊 Cassette Cliffs",
    "玫瑰花园 Rose Garden",
    "城市之上 Over the City",
    "如果我的“私人车道”让你差点死掉… If my 'driveway' almost did you in…",
    "树巢 Treehive",
    "潜在的一切 Potential for Anything",
    "对流层 Troposphere",
    "挤压 The Squeeze",
    "画境 paint",
    "香皂 Soap",
    "坠落谜题 Dropzle",
    "草莓果园 Strawberry Orchard",
    "来自星星的礼物 A Gift From the Stars",
    "管道与开关 Switchtube Vista",
    "被核心的城市 Coresaken City",
    "汤之海 Sea of Soup",
    "霜冻碎片 Frosted Fragments",
    "低重力植物园 Low-G Botany",
    "第五维度 Fifth Dimension",
    "星空之眠 Sleeping Under Stars",
    "净化行动 In Filtration",
    "工地难题 Construction Conundrum",
    "塔 The Tower",
    "眩晕 Vertigo",
    "深海迷航 Supernautica",
    "红蜜灯股份有限公司 Honeyzip Inc.",
    "吃豆女孩 EAT GIRL",
    "千空之寺 Temple of a Thousand Skies",
    "化方为圆 Square the Circle",
    "碧蓝 Deep Blue",
    "河豚运输有限公司 Pufferfish Transportation Co.",
    "午夜季风 Midnight Monsoon",
    "不知所谓的机器 Pointless Machines",
    "时之沙 Sands of Time",
    "史莱姆时间！Slime Time!",
    "死亡激光实验室 Lethal Laser Laboratory",
    "星空遗迹 Starry Ruins",
    "密林之下 Undergrowth",
    "迷失森林 Lost Woods",
    "金色黎明 Golden Dawn",
    "蜂之怒 Bee Berserk",
    "Java 的地下室 Java's Crypt",
    "炽热海沟 Tectonic Trenches",
    "水母圣所 Jellyfish Sanctum",
    "丛林快跑 Forest Rush",
    "克隆之击 Attack of the Clone",
    "雨落玫瑰 Raindrops on Roses",
    "开关理论 Toggle Theory",
    "上层建筑 Superstructure",
    "十六号 塔 The Tower (XVI)",
    "星光站 Starlight Station",
    "暮光之城 Dusk City",
    "突 触 Synapse",
    "实验室 The Lab",
    "虚空的召唤 Call of the Void",
    "颠倒洞穴 Rightside-Down Cavern",
    "传送门难题 Thinking with Portals",
    "迟来的情人节 Belated Valentine's Day",
    "飞翔的电池 Flying Battery",
    "核心问题 The Core Problem",
    "蔓生溪谷 Overgrown Linn",
    "水之冲击 Hydroshock",
    "地铁霓虹 Subway Neon",
    "毫无意义的装置 Meaningless Contraptions",
    "金色走廊 Golden Alleyway",
    "System.InvalidMapException",
    "变向 A Change in Direction",
    "天际篡夺者 Skyline Usurper",
    "钟塔 Clockwork",
    "等离子反应器 Plasma Reactor",
    "浮点 FLOATING POINT",
    "风暴行者 Storm Runner",
    "时间谜题 Time Trouble",
    "梦醒时分 Hypnagogia",
    "飘渺飞升 Ethereal Ascension",
    "纽带 Vinculum",
    "图腾花园 Mosaic Garden",
    "月之佛塔 Lunar Pagoda",
    "雀跃之舞 Caper Cavortion",
    "玛德琳：泡泡 Madeline：The Bubble",
    "斑斓色彩 Chromatic Complex",
    "秋色堡垒 Fortress Fall",
    "库塔拉花园 Garden of Khu'tara",
    "空洞狭缝 Narrow Hollow",
    "逆旅 Summit Down-Side",
    "北极星 Polaris",
    "意念力 Psychokinetic",
    "轮回疯狂B面 Cycle Madness B-Side",
    "熔岩层 Lava Layer",
    "kevintechspam.bin",
    "破空之虹 Fractured Iridescence",
    "超光速 Superluminary",
    "野兽之腹 Belly of the Beast",
    "猩空之穴 Cave of the Crimson Sky",
    "反转山脊 Flipside Cliffside",
    "漂泊深渊 Drifting Deep",
    "世界大穴 World Abyss",
    "星空奥德赛 Stellar Odyssey",
    "74",
    "崩碎之歌 Shattersong",
    "山顶 Summit",
    "象牙 Ivory",
    "弹球炼狱 Pinball Purgatory",
    "烈冕号 The Solar Express",
    "荷塘月色 Nelumbo",
    "蓝莓湾 Blueberry Bay",
    "树莓根下 Raspberry Roots",
    "金芒山 Mango Mesa",
    "杨桃星球 Starfruit Supernova",
    "百香万神殿 Passionfruit Pantheon",
]

prize={
		'蓝莓湾 Blueberry Bay': 0.1,
		'树莓根下 Raspberry Roots': 0.2,
		'金芒山 Mango Mesa': 0.3,
 		'杨桃星球 Starfruit Supernova': 0.5,
		'百香万神殿 Passionfruit Pantheon': 0.9,
		'74': "74",
		'十六号 塔 The Tower (XVI)': "16",
		'象牙 Ivory': 0.04,
		'弹球炼狱 Pinball Purgatory': 0.07,
		'荷塘月色 Nelumbo': 0.06,
		'烈冕号 The Solar Express': 0.05,
	}