"""插件内通用的常量（HTTP 状态码、超时等）。

各模块统一从这里取，别自己定义一份。
"""

HTTP_OK = 200
HTTP_NOT_FOUND = 404
HTTP_SERVER_ERROR = 500
HTTP_TOO_MANY_REQUESTS = 429
HTTP_BAD_GATEWAY = 502
HTTP_SERVICE_UNAVAILABLE = 503
HTTP_GATEWAY_TIMEOUT = 504

USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/151.0.0.0 Safari/537.36"
)

HTTP_TIMEOUT = 10
HTTP_RETRY_ATTEMPTS = 3
HTTP_RETRY_BACKOFF = 0.5
HTTP_RETRY_STATUS_CODES = frozenset(
    {
        HTTP_TOO_MANY_REQUESTS,
        HTTP_SERVER_ERROR,
        HTTP_BAD_GATEWAY,
        HTTP_SERVICE_UNAVAILABLE,
        HTTP_GATEWAY_TIMEOUT,
    }
)

# 查询源和渲染源都必须在有限时间内失败，不能拖住整个 matcher。
SOURCE_LOOKUP_TIMEOUT = 5
SEARCH_MAX_WORKERS = 3
